---
version: "2.1"
services:
  publisher:
    image: koti-publisher:0.0.1
    container_name: publisher
    ports:
      - 8080:8080
    volumes:
      - /mnt/shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  bme680:
    image: koti-bme680:0.0.1
    container_name: bme680
    volumes:
      - /mnt/shared:/shared
    privileged: true
    restart: unless-stopped
  